before:
  hooks:
    - go mod download
builds:
  -
    main: ./cmd/milo/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "github.com/wawandco/milo/cli/cmd/version.Version={{.Tag}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  -
    replacements:
      '386': i386
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'